# encoding: UTF-8
include_recipe 'LNPP::apt'
include_recipe 'user::data_bag'
include_recipe 'sudo::default'
include_recipe 'LNPP::ssh'
include_recipe 'LNPP::packages'
include_recipe 'LNPP::nginx'
include_recipe 'LNPP::percona'
include_recipe 'LNPP::projects'
include_recipe 'LNPP::php_fpm'
include_recipe 'composer::self_update'
include_recipe 'LNPP::munin'
